name: Andy Dote
description: Andy Dote's blog
url: https://andydote.co.uk
highlighter: rouge
exclude: [serve, servedrafts, vagrantfile]
paginate: 5
gems: [jekyll-paginate]
permalink: pretty

collections:
  - twelve
