name: Andy Dote
description: Andy Dote's blog
url: http://andydote.co.uk
highlighter: rouge
exclude: [serve, servedrafts, vagrantfile]
paginate: 5
gems: [jekyll-paginate]
permalink: pretty

ftp_host: 'andydote.co.uk'
ftp_dir: '/public_html'
ftp_passive: false
